### ISSUE TITLE
[meta task] Remove qt3support classes usage at all.

### ISSUE THREAD

**Issue by sergey-shambir** [DoUML/douml#53]
- [x] ```Q3PtrList``` should be replaced with ```QList```.
- [ ] ```Q3PopupMenu``` should be replaced with ```QMenu```.

The most problem is ```virtual void menu(const QPoint &) = 0;```, overriden in 115 classes. QMenu doesn't return index of selected option, as Q3PopupMenu does. Research ways to generalize context menu creation and maybe use ```std::function``` from C++ 2011.
- [ ] ```Q3ValueList``` should be replaced with ```QList```.
- [ ] ```Q3ListViewItem``` should be replaced.
- [ ] ```Q3Dict``` should be replaced.
- [ ] ```Q3PtrDict``` should be replaced.
- [ ] ```Q3CanvasItemList``` should be replaced.
- [ ] ```Q3CanvasRectangle``` should be replaced.
- [ ] Other classes also should be replaced with same classes from Qt4.
- [ ] finally, remove headers which names start with ```q3```.

**Comment by habipyesilyurt** [comment]
Qt5 port  solved this issue indirectly. #135

**Comment by mobius3** [comment]
Closing, then. Thanks.
